### ISSUE TITLE
Misc Fixes

### ISSUE THREAD

**Issue by finnbar** [the-Bruce/tgrsite#100]
Some small UI and db fixes.

- [x] Make notification icon more obvious (red, brighter or similar) when user has one or more unread notifications.
- [x] When user signs up, give Name field as optional, with description explaining that it helps people identify each other on the site.
- [x] Embed Google Calendar in website, including where/when our events and meetings are.
- [x] Increase forum body limit by 2x or 4x.

EDIT: THIS IS ISSUE 100, YAY! That's a success right

**Comment by the-Bruce** [comment]
How often are we running out of forum length in real usage?

**Comment by finnbar** [comment]
Ares ran out many times while adding meeting minutes (see early Term 1 minutes), but I actually fixed this before so closed.
