### ISSUE TITLE
Overhauled Minutes page

### ISSUE THREAD

**Issue by finnbar** [the-Bruce/tgrsite#103]
Ares wants a better place to put meeting minutes in a separate place, likely very similar to the Newsletters system. Don't need to notify people when new minutes are released though. :stuck_out_tongue: 

Could also have Google Slides embed? Might just be duplicating information at this point. Either way, requires more discussion with the overlord of spooky themselves.

**Comment by the-Bruce** [comment]
Closed by e074e7a
