### ISSUE TITLE
Site-side Image Uploads

### ISSUE THREAD

**Issue by finnbar** [the-Bruce/tgrsite#105]
Currently the only way to upload images to the site is via PythonAnywhere, which can only be done by the Web Admin. This is not entirely ideal. Need a way to upload images as an exec member to the server, probably via [this](https://help.pythonanywhere.com/pages/DjangoStaticFiles/).

**Comment by the-Bruce** [comment]
Fixed in 3e5796e64feebd2d35573984eaeaf216b38cda97
