### ISSUE TITLE
site redirects to https from localhost even when DEBUG is on

### ISSUE THREAD

**Issue by ashbc** [the-Bruce/tgrsite#106]
repro:

1. DEBUG=True in environment
2. Navigate to http://localhost:8000 - redirects to https://localhost:8000 and errors
3. Navigate to http://127.0.0.1:8000 - no redirect, site does what it should

OS: Windows 7 64-Bit SP1
Python version: 3.7.0
Django version: 2.1.4

**Comment by the-Bruce** [comment]
This seems to be due to the 301 redirects being cashed by the browser (at least when it happens to me). If you were to try and visit 127.0.0.1 with debug off, and then again with debug on, i suspect the same would happen.

Clearing the browser cache should fix this.

**Comment by the-Bruce** [comment]
Can't fix. New local_config.py file capability should help if it contains:
```
DEBUG = True
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
```
