### ISSUE TITLE
Markdown rendering of lists is questionable

### ISSUE THREAD

**Issue by finnbar** [the-Bruce/tgrsite#107]
The markdown list

```
**Here's a list**
* list 1
* list 2
```

doesn't render the list. If you add a newline before the list however, like so:

```
**Here's a list**

* list 1
* list 2
```

it works fine. I don't know whether this is part of the markdown spec, but it's a tiny bit annoying and might be worth at least documenting.

**Comment by finnbar** [comment]
Just to see if Github Markdown does it:

**Example 1**
* list 1
* list 2

and

**Example 2**

* list 1
* list 2

**Comment by the-Bruce** [comment]
This is an interesting one. Looking at the references I can find, this appears to be an implicit part of the format. It implies in the specification that every block level markup element should be separated by white space lines, but it's not actually stated as such. Additionally, every example listed within it showing lists puts the new lines in. Renderes, as you showed, are inconsistent in the application of that 'rule'.
