### ISSUE TITLE
site doesn't work without "www" subdomain

### ISSUE THREAD

**Issue by ashbc** [the-Bruce/tgrsite#175]
https://warwicktabletop.co.uk/ gives an "unable to connect" error. User agent: Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

Can't remember if this used to work, or if it's a restriction to do with how pythonanywhere works, or what, but it seems pretty bad

**Comment by the-Bruce** [comment]
Hmm. This is an unfortunate corner case, it only happens on https, as http forwarding has been set up. I'll see if I can fix it using gandi, as I'm pretty certain there isn't anything I can do on the pythonanywhere side.

**Comment by the-Bruce** [comment]
Yep. Fixed it in gandi.
