### ISSUE TITLE
Notifications 2.0

### ISSUE THREAD

**Issue by finnbar** [the-Bruce/tgrsite#92]
Beta notifications are written in the notifications branch. For better notifications however, we should consider the following:

* Split notifications into categories.
* Merge notifications by category and URL (e.g. all event joins in one place which link to all events in question).
* Maybe an email digest of unread notifications after a while?
* `@` notifications in forums etc.
* Email notifications???

**Comment by the-Bruce** [comment]
Most of these (except merging as I'm not sure how to deal with stuff like time mismatch) are implemented in d65ebbfcea6738abbf61044736e2f79d9d033881.
