### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by ashbc** [the-Bruce/tgrsite#96]
I have no idea how to do SEO, but our site could use it. For searches like "warwick dnd", "warwick wargames", "warwick dnd", etc., we aren't particularly high on the ranks.

**Comment by the-Bruce** [comment]
Some progress mage in 1f510da1eebdb705c67c6147d4a9c459c8b59f79

**Comment by the-Bruce** [comment]
Now much higher up the rankings for this sort of search. Not sure how much more we can do. Closing this for now.
